[package]
name = "moq-trace"
description = "MoQ object instrumentation layered over quic-trace."
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
lttng = ["dep:moq-trace-lttng-sys", "quic-trace/lttng"]

[dependencies]
moq-trace-lttng-sys = { workspace = true, optional = true }
quic-trace.workspace = true
trace-core.workspace = true

[dev-dependencies]
trace-core = { workspace = true, features = ["recording"] }
