[package]
name = "quic-trace"
description = "Typed transport instrumentation for QUIC implementations."
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
lttng = ["dep:quic-trace-lttng-sys", "trace-core/lttng"]

[dependencies]
quic-trace-lttng-sys = { workspace = true, optional = true }
trace-core.workspace = true

[dev-dependencies]
trace-core = { workspace = true, features = ["recording"] }
